import { Nationalities, PlayerSeasonStats } from "./misc";
import PlayerPhoto from '../public/player.png';
import NunoReisImg from '../public/players/nuno-reis.png';
import BernardoFigueiredoImg from '../public/players/bernardo-figueiredo.png';
import DiogoDominguesImg from '../public/players/diogo-domingues.png';
import LucasGarciaImg from '../public/players/lucas-garcia.png';
import RenatoOliveiraImg from '../public/players/renato-oliveira.png';
import TomasSantosImg from '../public/players/tomas-santos.png';
import RubenRodriguesImg from '../public/players/ruben-rodrigues.png';
import { ExtendedTeamPlayer, TeamPlayer } from "../types/types";
import { StaticImageData } from "next/image";

export const AndreSalvado: ExtendedTeamPlayer = {
    firstName: 'André',
    lastName: 'Salvado',
    photoUrl: PlayerPhoto,
    clubNumber: 8,
    stats: {
        ATA: 79,
        DEF: 75,
        TEC: 72,
        WR: 80,
        AGRE: 67,
        RES: 77,
        FIN: 67,
        SPE: 64,
        DRI: 77,
        PHY: 68,
        PAS: 76,
        OVR: 74,
    },
    nationality: [Nationalities.PT],
    nickName: 'A. SALVADO',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 1,
    lastModifiedDate: '',
    userId: 1,
    wildcard: false,
};

export const AlexandreSantos: ExtendedTeamPlayer = {
    firstName: 'Alexandre',
    lastName: 'Santos',
    photoUrl: PlayerPhoto,
    clubNumber: 31,
    stats: {
        ATA: 82,
        DEF: 63,
        TEC: 87,
        WR: 65,
        AGRE: 61,
        RES: 64,
        FIN: 70,
        SPE: 75,
        DRI: 88,
        PHY: 61,
        PAS: 82,
        OVR: 72,
    },
    nationality: [Nationalities.PT],
    nickName: 'LEVEZINHO',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 2,
    lastModifiedDate: '',
    userId: 2,
    wildcard: false,
};

export const BernardoFigueiredo: ExtendedTeamPlayer = {
    firstName: 'Bernardo',
    lastName: 'Figueiredo',
    photoUrl: BernardoFigueiredoImg,
    clubNumber: 65,
    stats: {
        ATA: 60,
        DEF: 74,
        TEC: 57,
        WR: 98,
        AGRE: 97,
        RES: 77,
        FIN: 61,
        SPE: 76,
        DRI: 58,
        PHY: 81,
        PAS: 60,
        OVR: 72,
    },
    nationality: [Nationalities.PT],
    nickName: 'BERNARDO',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 3,
    lastModifiedDate: '',
    userId: 3,
    wildcard: false,
    
};

export const DiogoDomingues: ExtendedTeamPlayer = {
    firstName: 'Diogo',
    lastName: 'Domingues',
    photoUrl: DiogoDominguesImg,
    clubNumber: 1,
    stats: {
        ATA: 61,
        DEF: 65,
        TEC: 51,
        WR: 86,
        AGRE: 91,
        RES: 74,
        FIN: 62,
        SPE: 75,
        DRI: 52,
        PHY: 74,
        PAS: 55,
        OVR: 67,
    },
    nationality: [Nationalities.PT],
    nickName: 'PIRATA',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 4,
    lastModifiedDate: '',
    userId: 4,
    wildcard: false,
};

export const FranciscoMachado: ExtendedTeamPlayer = {
    firstName: 'Francisco',
    lastName: 'Machado',
    photoUrl: PlayerPhoto,
    clubNumber: 5,
    stats: {
        AGRE: 51,
        ATA: 41,
        DEF: 44,
        DRI: 40,
        FIN: 45,
        OVR: 49,
        PAS: 50,
        PHY: 85,
        RES: 55,
        SPE: 45,
        TEC: 40,
        WR: 41,
    },
    nationality: [Nationalities.PT],
    nickName: 'MACHADO',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 5,
    lastModifiedDate: '',
    userId: 5,
    wildcard: false,
};

export const GustavoCarreira: ExtendedTeamPlayer = {
    firstName: 'Gustavo',
    lastName: 'Carreira',
    photoUrl: PlayerPhoto,
    clubNumber: 6,
    stats: {
        ATA: 52,
        DEF: 50,
        TEC: 45,
        WR: 53,
        AGRE: 65,
        RES: 61,
        FIN: 58,
        SPE: 52,
        DRI: 47,
        PHY: 68,
        PAS: 52,
        OVR: 55,
    },
    nationality: [Nationalities.PT],
    nickName: 'CARREIRA',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 6,
    lastModifiedDate: '',
    userId: 6,
    wildcard: false,
};

export const IvoOliveira: ExtendedTeamPlayer = {
    firstName: 'Ivo',
    lastName: 'Oliveira',
    photoUrl: PlayerPhoto,
    clubNumber: 11,
    stats: {
        ATA: 89,
        DEF: 67,
        TEC: 90,
        WR: 65,
        AGRE: 70,
        RES: 67,
        FIN: 89,
        SPE: 54,
        DRI: 90,
        PHY: 93,
        PAS: 86,
        OVR: 79,
    },
    nationality: [Nationalities.PT],
    nickName: 'OLIVEIRA',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 7,
    lastModifiedDate: '',
    userId: 7,
    wildcard: false,
};

export const JoaoFerreira: ExtendedTeamPlayer = {
    firstName: 'João',
    lastName: 'Ferreira',
    photoUrl: PlayerPhoto,
    clubNumber: 10,
    stats: {
        ATA: 89,
        DEF: 76,
        TEC: 90,
        WR: 81,
        AGRE: 78,
        RES: 73,
        FIN: 75,
        SPE: 83,
        DRI: 91,
        PHY: 67,
        PAS: 86,
        OVR: 80,
    },
    nationality: [Nationalities.PT],
    nickName: 'J. FERREIRA',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 8,
    lastModifiedDate: '',
    userId: 8,
    wildcard: false,
};

export const JoaoMota: ExtendedTeamPlayer = {
    firstName: 'João',
    lastName: 'Mota',
    photoUrl: PlayerPhoto,
    clubNumber: 42,
    stats: {
        ATA: 44,
        DEF: 52,
        TEC: 43,
        WR: 47,
        AGRE: 60,
        RES: 51,
        FIN: 51,
        SPE: 46,
        DRI: 47,
        PHY: 61,
        PAS: 52,
        OVR: 50,
    },
    nationality: [Nationalities.PT],
    nickName: 'MOTALLICA',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 9,
    lastModifiedDate: '',
    userId: 9,
    wildcard: false,

};

export const JoaoPaulino: ExtendedTeamPlayer = {
    firstName: 'João',
    lastName: 'Paulino',
    photoUrl: PlayerPhoto,
    clubNumber: 7,
    stats: {
        ATA: 80,
        DEF: 80,
        TEC: 74,
        WR: 79,
        AGRE: 66,
        RES: 76,
        FIN: 72,
        SPE: 66,
        DRI: 80,
        PHY: 66,
        PAS: 76,
        OVR: 75,
    },
    nationality: [Nationalities.PT],
    nickName: 'PAULINO',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 10,
    lastModifiedDate: '',
    userId: 10,
    wildcard: false,
};

export const JorgeFerreira: ExtendedTeamPlayer = {
    firstName: 'Jorge',
    lastName: 'Ferreira',
    photoUrl: PlayerPhoto,
    clubNumber: 97,
    stats: {
        ATA: 67,
        DEF: 76,
        TEC: 64,
        WR: 78,
        AGRE: 76,
        RES: 76,
        FIN: 71,
        SPE: 62,
        DRI: 61,
        PHY: 85,
        PAS: 67,
        OVR: 72,
    },
    nationality: [Nationalities.PT],
    nickName: 'JORGE M.',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 11,
    lastModifiedDate: '',
    userId: 11,
    wildcard: false,
};

export const JosePedrosa: ExtendedTeamPlayer = {
    firstName: 'José',
    lastName: 'Pedrosa',
    photoUrl: PlayerPhoto,
    clubNumber: 80,
    stats: {
        ATA: 90,
        DEF: 70,
        TEC: 87,
        WR: 77,
        AGRE: 72,
        RES: 74,
        FIN: 87,
        SPE: 73,
        DRI: 87,
        PHY: 81,
        PAS: 87,
        OVR: 81,
    },
    nationality: [Nationalities.PT],
    nickName: 'PEDROSA',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 12,
    lastModifiedDate: '',
    userId: 12,
    wildcard: false,
};

export const LucasGarcia: ExtendedTeamPlayer = {
    firstName: 'Lucas',
    lastName: 'Garcia',
    photoUrl: LucasGarciaImg,
    clubNumber: 9,
    stats: {
        ATA: 87,
        DEF: 60,
        TEC: 84,
        WR: 58,
        AGRE: 79,
        RES: 63,
        FIN: 94,
        SPE: 57,
        DRI: 81,
        PHY: 84,
        PAS: 81,
        OVR: 75,
    },
    nationality: [Nationalities.BRA, Nationalities.PT],
    nickName: 'LUKAKU',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 13,
    lastModifiedDate: '',
    userId: 13,
    wildcard: false,
};

export const NunoReis: ExtendedTeamPlayer = {
    firstName: 'Nuno',
    lastName: 'Reis',
    photoUrl: NunoReisImg,
    clubNumber: 17,
    stats: {
        ATA: 92,
        DEF: 91,
        TEC: 89,
        WR: 97,
        AGRE: 97,
        RES: 96,
        FIN: 94,
        SPE: 87,
        DRI: 88,
        PHY: 86,
        PAS: 85,
        OVR: 91,
    },
    nationality: [Nationalities.PT],
    nickName: 'RUNO NEIS',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 14,
    lastModifiedDate: '',
    userId: 14,
    wildcard: false,
};

export const RenatoOliveira: ExtendedTeamPlayer = {
    firstName: 'Renato',
    lastName: 'Oliveira',
    photoUrl: RenatoOliveiraImg,
    clubNumber: 68,
    stats: {
        ATA: 51,
        DEF: 53,
        TEC: 51,
        WR: 62,
        AGRE: 56,
        RES: 58,
        FIN: 55,
        SPE: 53,
        DRI: 50,
        PHY: 61,
        PAS: 50,
        OVR: 55,
    },
    nationality: [Nationalities.PT],
    nickName: 'RENATO',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 15,
    lastModifiedDate: '',
    userId: 15,
    wildcard: false,
};

export const RubenRodrigues: ExtendedTeamPlayer = {
    firstName: 'Rúben',
    lastName: 'Rodrigues',
    photoUrl: RubenRodriguesImg,
    clubNumber: 20,
    stats: {
        ATA: 83,
        DEF: 70,
        TEC: 82,
        WR: 64,
        AGRE: 67,
        RES: 74,
        FIN: 75,
        SPE: 72,
        DRI: 82,
        PHY: 67,
        PAS: 76,
        OVR: 74,
    },
    nationality: [Nationalities.PT],
    nickName: 'AQUAMAN',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 16,
    lastModifiedDate: '',
    userId: 16,
    wildcard: false,
};

export const TomasSantos: ExtendedTeamPlayer = {
    firstName: 'Tomás',
    lastName: 'Santos',
    photoUrl: TomasSantosImg,
    clubNumber: 27,
    stats: {
        ATA: 58,
        DEF: 54,
        TEC: 58,
        WR: 60,
        AGRE: 57,
        RES: 56,
        FIN: 54,
        SPE: 55,
        DRI: 54,
        PHY: 61,
        PAS: 58,
        OVR: 57,
    },
    nationality: [Nationalities.PT],
    nickName: 'SANTOS',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 17,
    lastModifiedDate: '',
    userId: 17,
    wildcard: false,
};

export const RodrigoAlves: ExtendedTeamPlayer = {
    firstName: 'Rodrigo',
    lastName: 'Alves',
    photoUrl: PlayerPhoto,
    clubNumber: 16,
    stats: {
        ATA: 56,
        DEF: 51,
        TEC: 56,
        WR: 59,
        AGRE: 55,
        RES: 56,
        FIN: 50,
        SPE: 51,
        DRI: 50,
        PHY: 60,
        PAS: 55,
        OVR: 55,
    },
    nationality: [Nationalities.PT],
    nickName: 'R. ALVES',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 18,
    lastModifiedDate: '',
    userId: 18,
    wildcard: false,
}

export const WildCard: ExtendedTeamPlayer = {
    firstName: 'Wildcard',
    lastName: '1',
    photoUrl: PlayerPhoto,
    clubNumber: 99,
    stats: {
        ATA: 56,
        DEF: 51,
        TEC: 56,
        WR: 59,
        AGRE: 55,
        RES: 56,
        FIN: 50,
        SPE: 51,
        DRI: 50,
        PHY: 60,
        PAS: 55,
        OVR: 55,
    },
    nationality: [Nationalities.PT],
    nickName: 'WILDCARD #1',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 19,
    lastModifiedDate: '',
    userId: 19,
    wildcard: true,
};
export const AlexandreLopes: ExtendedTeamPlayer = {
    firstName: 'Alexandre',
    lastName: 'Lopes',
    photoUrl: PlayerPhoto,
    clubNumber: 94,
    stats: {
        ATA: 56,
        DEF: 51,
        TEC: 56,
        WR: 59,
        AGRE: 55,
        RES: 56,
        FIN: 50,
        SPE: 51,
        DRI: 50,
        PHY: 60,
        PAS: 55,
        OVR: 55,
    },
    nationality: [Nationalities.PT],
    nickName: 'ALEX LOPES',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 20,
    lastModifiedDate: '',
    userId: 20,
    wildcard: false,
}

export const PedroLopes: ExtendedTeamPlayer = {
    firstName: 'Pedro',
    lastName: 'Lopes',
    photoUrl: PlayerPhoto,
    clubNumber: 88,
    stats: {
        ATA: 56,
        DEF: 51,
        TEC: 56,
        WR: 59,
        AGRE: 55,
        RES: 56,
        FIN: 50,
        SPE: 51,
        DRI: 50,
        PHY: 60,
        PAS: 55,
        OVR: 55,
    },
    nationality: [Nationalities.PT],
    nickName: 'LEDRO POPES',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 21,
    lastModifiedDate: '',
    userId: 21,
    wildcard: false,
}

export const PedroGoncalves: ExtendedTeamPlayer = {
    firstName: 'Pedro',
    lastName: 'Gonçalves',
    photoUrl: PlayerPhoto,
    clubNumber: 4,
    stats: {
        ATA: 79,
        DEF: 75,
        TEC: 90,
        WR: 64,
        AGRE: 65,
        RES: 69,
        FIN: 80,
        SPE: 68,
        DRI: 90,
        PHY: 61,
        PAS: 80,
        OVR: 75,
    },
    nationality: [Nationalities.PT],
    nickName: 'ROCAS',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 22,
    lastModifiedDate: '',
    userId: 22,
    wildcard: false,
};

export const AlexandreMendes: ExtendedTeamPlayer = {
    firstName: 'Alexandre',
    lastName: 'Mendes',
    photoUrl: PlayerPhoto,
    clubNumber: 90,
    stats: {
        ATA: 56,
        DEF: 51,
        TEC: 56,
        WR: 59,
        AGRE: 55,
        RES: 56,
        FIN: 50,
        SPE: 51,
        DRI: 50,
        PHY: 60,
        PAS: 55,
        OVR: 55,
    },
    nationality: [Nationalities.PT],
    nickName: 'MENDES',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 23,
    lastModifiedDate: '',
    userId: 23,
    wildcard: false,
}

export const LuisSantos: ExtendedTeamPlayer = {
    firstName: 'Luis',
    lastName: 'Santos',
    photoUrl: PlayerPhoto,
    clubNumber: 95,
    stats: {
        ATA: 56,
        DEF: 51,
        TEC: 56,
        WR: 59,
        AGRE: 55,
        RES: 56,
        FIN: 50,
        SPE: 51,
        DRI: 50,
        PHY: 60,
        PAS: 55,
        OVR: 55,
    },
    nationality: [Nationalities.PT],
    nickName: 'L. SANTOS',
    goals: 0,
    assists: 0,
    createdDate: '',
    id: 24,
    lastModifiedDate: '',
    userId: 24,
    wildcard: false,
}